FROM node:20-bookworm-slim

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY prisma ./prisma
COPY tsconfig.json ./tsconfig.json

RUN npx prisma generate

CMD ["sh", "-c", "npx prisma migrate deploy && npx tsx prisma/seed.ts"]
